version: "2"

services:
  vscode:
    image: sebmoule/docker-vscode-chris
    environment:
      - "DISPLAY=${DISPLAY}"
    hostname: vscode
    tty: true
    stdin_open: true
    network_mode: host
    volumes:
      - ${HOME}:${HOME}
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: vscode
#    user: root
